### ISSUE TITLE
OpenTOSCA Instances Details View

### ISSUE THREAD

**Issue by bigal91** [CloudCycle2/CSAR_Repository#181]
Diese Detail Ansicht für die OT-Instance muss:
* einen Vinothek Link unterstützen (Schema ist host:port/vinothek/)
* (vorerst) einen Admin-UI Link für die OT-Instance unterstützen
* eine Tabelle mit deployed CSARs muss angezeigt werden

**Comment by eiselems** [comment]
@bigal91 muss die Tabelle wirklich die deployed CSARs anzeigen? oder eher alle deployed CsarFiles (vielleicht inklusive der zugehörigen CSAR als Spalte)?

**Comment by bigal91** [comment]
@eiselems das kommt darauf an, ob wir uns CSARs oder CSAR-Files merken wollen, die wir auf eine OT Instanz gepushed haben. Soweit ich weiß haben wir uns auf die einzelnen CSAR Files geeinigt? oder? Wenn ja muss das Modell ebenfalls angepasst werden.
