### ISSUE TITLE
GUI Consistency

### ISSUE THREAD

**Issue by bigal91** [CloudCycle2/CSAR_Repository#272]
The GUI should show consistency in every view.
Try to do the following:
1.) The offset of Adding File (Input Fields) or showing Information (Textfieds) should be the same. And maybe not 100% Width, it is unlikely that the whole page-width is needed.
2.) Link Opening should be consistent (OT Server "Visit Containerapi" and Winery "visit Winery" Links for example should be the same)

=== View specific changes: ===

added from #341:
csarDetailView should show the name and namespace of the csar's serviceTemplate.

Please also take a look atthe following screenshots of the current version (date: 03.02.2015)

# CSARs View
![csars](https://cloud.githubusercontent.com/assets/6729367/6021312/2b10bd74-abb5-11e4-95d7-10087db7c57c.png)

# CSAR-FILES View
![csarfiles](https://cloud.githubusercontent.com/assets/6729367/6021319/376c093e-abb5-11e4-8876-bd51043c9028.png)

# OPENTOSCA_SERVER_MANAGE
![otservers](https://cloud.githubusercontent.com/assets/6729367/6021326/41b3a0e6-abb5-11e4-9996-6999d2689fcd.png)

# OPENTOSCA_SERVER_DETAILS_VIEW
![otserver_details](https://cloud.githubusercontent.com/assets/6729367/6021330/4916f2f2-abb5-11e4-93bd-7a413af3d803.png)

# WINERY_MANAGE
![wineryservers](https://cloud.githubusercontent.com/assets/6729367/6021334/5046efc8-abb5-11e4-84db-665546e35325.png)

# WINERY_DETAILS_VIEW
![winerydetails](https://cloud.githubusercontent.com/assets/6729367/6021339/56c10492-abb5-11e4-9a76-43de72f3e680.png)

**Comment by Nik101010** [comment]
@CloudCycle2/entwicklungsprojekt I'd suggest we refactor all views to the tab layout used for csars? Any other opinions?

**Comment by eiselems** [comment]
Think the tabbed layout is pretty neat. I agree on using it.

**Comment by TKosch** [comment]
Isn't the GUI already consistent? Do you find any inconsistencies?

**Comment by Nik101010** [comment]
1) CSAR - importing from winery or creating a new one is in one view vs. CsarFiles its in two different tabs
2) Rename and delete for CSAR is in a seperate tab vs. all other views have it somewhere in the overview
3) CSAR has an Operations tabbar vs. CsarFiles, winery have the operations like import new csar, export to winery, deploy on ot instance as headings within the page though these are operations

**Comment by eiselems** [comment]
added details from #341 to the description of the issue
