### ISSUE TITLE
Live Daten für die OT-Ansicht

### ISSUE THREAD

**Issue by bigal91** [CloudCycle2/CSAR_Repository#299]

**Comment by bigal91** [comment]
![unbenannt3](https://cloud.githubusercontent.com/assets/6729367/6131991/11070ac8-b150-11e4-84e6-0c0ab2534a42.png)

**Comment by eiselems** [comment]
@bigal91 definition of done: Showing all RUNNING (,created by a build plan) Instances?

**Comment by bigal91** [comment]
Yes, as far as i understood it we only need to show the Running instances, which have been started (after BUILD PLAN Execution).

**Comment by eiselems** [comment]
ok, got an almost working solution. Still a few unresolved issues (i.e. handling not reachable OpenTOSCA-Servers)

**Comment by eiselems** [comment]
closed by #317
