### ISSUE TITLE
Starten von Plänen

### ISSUE THREAD

**Issue by bigal91** [CloudCycle2/CSAR_Repository#301]
Pläne sollen direkt über den BPS gestartet werden können (nicht wie vorher angenommen über den Service Invoker).

Vermutlich soll diese Funktionalität dann in der CSAR-File Ansicht möglich gemacht werden (als "Action" in der Tabelle, in der gezeigt ist, auf welchen OT-Servern die CSAR-File deployed ist)

**Comment by eiselems** [comment]
Die Funktionalität heißt "Try-it" und ist als URL direkt im BPS verfügbar.
Man muss halt noch schauen wie der Link genau gebaut wird.

Drauf achten, dass man vielleicht die https-Variante nimmt weil sonst oben immer ne nervige Warnung kommt.
