### ISSUE TITLE
CSAR / CSAR-Files zeigen wo sie deployed werden.

### ISSUE THREAD

**Issue by bigal91** [CloudCycle2/CSAR_Repository#302]
Fehlt afaik nurnoch für die CSARs selber (analog ist dies schon für CSAR-Files implementiert, siehe CSAR-FILE Detailansicht)

**Comment by bigal91** [comment]
@ mich selbst, nochmal checken, was damit gemeint war

**Comment by eiselems** [comment]
Still needs the GUI implementation
