### ISSUE TITLE
Create an additional OpenTOSCA test environment

### ISSUE THREAD

**Issue by eiselems** [CloudCycle2/CSAR_Repository#304]
I think it would be cool to have an OpenTOSCA Instance (including the whole OT ecosystem vinothek, winery) for testing purposes, i.e. having an OpenTOSCA instance which could be attached to the developers' workspace CsarRepo.

The current one is fine but is used by our TestInstance of the CsarRepo. Using it for tests will interfere / break the state of the test csarRepo for our customers.

@bigal91 think it would be a nice task for you, because you have already installed the first instance including solving some problems

**Comment by bigal91** [comment]
Sorry for long delay, didnt get to this before my exam.

I created a new, empty (meaning no CSARs in it) OpenTOSCA Environment with a Winery, a Vinothek and of course OpenTOSCA itself. You can access it here:

http://192.168.209.249:8080/
