### ISSUE TITLE
convert url to link in OTServerDetail Servlet

### ISSUE THREAD

**Issue by eiselems** [CloudCycle2/CSAR_Repository#321]
http://localhost:8080/csarrepo/opentoscaserverlist

**Comment by Nik101010** [comment]
I'm not sure if we should display the link there? Maybe just show it in the detail view?

**Comment by przytads** [comment]
I will convert the URL to Link in OpenTOSCA and Winery.
Removing it lets the table look empty (only id and name remaining).
