### ISSUE TITLE
Create ServiceInstanceView

### ISSUE THREAD

**Issue by eiselems** [CloudCycle2/CSAR_Repository#334]
Create view to show details about a serviceInstance (you don't say :smile: )

* Link to CSAR Detailview
* Link to InstanceData-API (serviceInstance specific link)
* Way to invoke terminationPlan

**Comment by eiselems** [comment]
There are just ManagementPlans (a termination plan is a sort of ManagementPlan).

**Comment by TKosch** [comment]
Cool, good to know!
