### ISSUE TITLE
CsarDetailView is missing details

### ISSUE THREAD

**Issue by eiselems** [CloudCycle2/CSAR_Repository#341]
The view only shows the name as title, maybe we should add the namespace?

Should we also list existing plans?

**Comment by bigal91** [comment]
@eiselems 
show namespace - yes i would say
list existing plans? - was not really a requirement... so i guess this is a No (or at least very low priority)

**Comment by eiselems** [comment]
just wanted to mention it, i just implemented the storage of the plans inside the csar (therefore it would only be an iteration over the plan map keys to retrieve the information)

but i can live without the plans inside the view :wink:

**Comment by eiselems** [comment]
After rethinking, we have to view the ID and the namespace of the template (our name has not to be equal to the id of the serviceTemplate)

**Comment by Nik101010** [comment]
I'd add this together with #272 ? Otherwise we're running in merge conflicts I guess...

**Comment by eiselems** [comment]
i don't mind by which issue this will be targeted :stuck_out_tongue_winking_eye:.
You can close this issue and address it inside #272
